/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author DETEC_IT
 */
import dao.conectaBanco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

public class CadPessoa extends javax.swing.JDialog implements control.Controlos {

    /**
     * Creates new form CadastroInfracao
     */
    conectaBanco connect = new conectaBanco();

    public CadPessoa() {
        initComponents();
        Desabilitar();
        connect.conexao();
      // jPanel2.setBackground(new Color(0,0,0,125));
    }

    public CadPessoa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Desabilitar();
        connect.conexao();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfApelido = new javax.swing.JTextField();
        tfNacionalidade = new javax.swing.JTextField();
        btn_novo = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        cbSexo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        tfQuarteirao = new javax.swing.JTextField();
        tfRua_av = new javax.swing.JTextField();
        tfResid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfDistritoNasc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfNmrDoc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbProvinciaResid = new javax.swing.JComboBox();
        cbTipoDoc = new javax.swing.JComboBox();
        cbProvinciaNasc = new javax.swing.JComboBox();
        btn_atualizar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tfProf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfDataNasc = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRM");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        jLabel1.setText("* Nome ");

        jLabel2.setText("* Apelido");

        jLabel3.setText("* Data de nascimento");

        jLabel4.setText("* Nacionalidade");

        tfNome.setDocument(new MeuDocument(100));
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfApelido.setDocument(new MeuDocument(45));

        tfNacionalidade.setDocument(new MeuDocument(45));

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---------selecione---------", "M", "F" }));

        jLabel6.setText("* Sexo");

        tfQuarteirao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuarteiraoKeyTyped(evt);
            }
        });

        tfRua_av.setDocument(new MeuDocument(100));

        tfResid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResidActionPerformed(evt);
            }
        });
        tfResid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfResidKeyTyped(evt);
            }
        });

        jLabel8.setText("Rua/Avenida");

        jLabel9.setText("* Bairro");

        jLabel10.setText("Quarteirão");

        jLabel11.setText("Nº da residência");

        jLabel12.setText("* Destrito");

        jLabel13.setText("* Local de residência");

        tfDistritoNasc.setDocument(new MeuDocument(45));

        jLabel14.setText("* Tipo de Documento");

        jLabel15.setText("* Nº do Documento");

        tfNmrDoc.setDocument(new MeuDocument(13));
        tfNmrDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNmrDocKeyTyped(evt);
            }
        });

        jLabel16.setText("* Naturalidade");

        cbProvinciaResid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----------------------------selecione-----------------------------", "Niassa", "Cabo Delgado", "Nampula", "Zambézia", "Tete", "Manica", "Sofala", "Inhambane", "Gaza", "Maputo (província)", "Maputo (cidade)" }));

        cbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----------------------------Selecione----------------------", "Bilhete de Identidade", "Boletim de Nascimento", "Passaporte" }));
        cbTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDocActionPerformed(evt);
            }
        });

        cbProvinciaNasc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----------------------------------selecione-------------------------------", "Niassa", "Cabo Delgado", "Nampula", "Zambézia", "Tete", "Manica", "Sofala", "Inhambane", "Gaza", "Maputo (província)", "Maputo (cidade)" }));

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        jLabel17.setText("*  Campos Obrigatórios");

        tfProf.setDocument(new MeuDocument(45));

        jLabel19.setText("Profissão");

        try {
            tfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNmrDoc)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbTipoDoc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDistritoNasc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProvinciaNasc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel14))
                    .addComponent(jLabel15)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(tfApelido)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfDataNasc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(tfNome)
                    .addComponent(jLabel4)
                    .addComponent(tfNacionalidade))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfQuarteirao)
                    .addComponent(tfBairro)
                    .addComponent(tfRua_av)
                    .addComponent(tfResid)
                    .addComponent(tfProf)
                    .addComponent(cbProvinciaResid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel19)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProvinciaResid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNmrDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuarteirao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRua_av, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfResid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfProf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbProvinciaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(8, 8, 8)
                .addComponent(tfDistritoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(java.awt.SystemColor.windowBorder);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/prm-logo.jpg"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel18.setText("PRM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
        if (cbTipoDoc.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione o tipo de Documento!", "Atenção", JOptionPane.WARNING_MESSAGE);
            cbTipoDoc.requestFocus();
            return;
        }
        if (tfNmrDoc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo número de documento!", "Atenção", JOptionPane.WARNING_MESSAGE);
            tfNmrDoc.requestFocus();
            return;
        }

        if (tfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome!", "Atenção", JOptionPane.WARNING_MESSAGE);
            tfNome.requestFocus();
            return;
        }
        if (tfApelido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Apelido!", "Atenção", JOptionPane.WARNING_MESSAGE);
            tfApelido.requestFocus();
            return;
        }
        if (tfDataNasc.getText().equals("    /  /  ")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Data de Nascimento!", "Atenção", JOptionPane.WARNING_MESSAGE);
            tfDataNasc.requestFocus();
            return;
        }
        if (cbSexo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione o Sexo!", "Atenção", JOptionPane.WARNING_MESSAGE);
            cbSexo.requestFocus();
            return;
        }
        if (tfNacionalidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nacionalidade!", "Atenção", JOptionPane.WARNING_MESSAGE);
            tfNacionalidade.requestFocus();
            return;
        }

        if (cbProvinciaNasc.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione o Província!", "Atenção", JOptionPane.WARNING_MESSAGE);
            cbProvinciaNasc.requestFocus();
            return;
        }

        if (tfDistritoNasc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Distrito!", "Atenção", JOptionPane.WARNING_MESSAGE);
            tfDistritoNasc.requestFocus();
            return;
        }

        if (cbProvinciaResid.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione o Local de residência!", "Atenção", JOptionPane.WARNING_MESSAGE);
            cbProvinciaResid.requestFocus();
            return;
        }
        if (tfDistritoNasc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Destrito!", "Atenção", JOptionPane.WARNING_MESSAGE);
            tfDistritoNasc.requestFocus();
            return;
        }
        if (tfBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Bairro!", "Atenção", JOptionPane.WARNING_MESSAGE);
            tfBairro.requestFocus();
            return;
        }

        try {//prepara o codigo SQL
            String sql = "insert into PESSOA (Tipo_DOC, BI_passaport, Nome, apelido, Data_Nasc, Sexo, nacionalidade,"
                    + "Provincia_Nasc, Distrito_Cidade_Nasc, Provincia_Resid, profissao,\n"
                    + "Bairro_Resid, quarteirao_resid,av_rua_resid, nr_resid)\n"
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement stm = connect.conn.prepareStatement(sql);

            stm.setString(1, cbTipoDoc.getSelectedItem().toString());
            stm.setString(2, tfNmrDoc.getText());
            stm.setString(3, tfNome.getText());
            stm.setString(4, tfApelido.getText());
            stm.setString(5, tfDataNasc.getText());
            stm.setString(6, cbSexo.getSelectedItem().toString());
            stm.setString(7, tfNacionalidade.getText());
            stm.setString(8, cbProvinciaNasc.getSelectedItem().toString());
            stm.setString(9, tfDistritoNasc.getText());
            stm.setString(10, cbProvinciaResid.getSelectedItem().toString());
            stm.setString(11, tfProf.getText());
            stm.setString(12, tfBairro.getText());
            stm.setString(13, tfQuarteirao.getText());
            stm.setString(14, tfRua_av.getText());
            stm.setString(15, tfResid.getText());

            stm.executeUpdate(); //faz um update/atualizacao na base de dads para poder registar
            JOptionPane.showMessageDialog(null, "Dados Registados com sucesso!");
            //connect.desconecta();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Falha ao registar os dados!\nContacte o Administrador do sistema" + erro);
        }

        Limpar();
        Desabilitar();
        btn_novo.setEnabled(true);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void cbTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDocActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        Habilitar();
        cbTipoDoc.requestFocus();
        btn_novo.setEnabled(false);
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        Limpar();
        Desabilitar();
        btn_novo.setEnabled(true);

    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void tfNmrDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNmrDocKeyTyped
        // TODO add your handling code here:
       /*if(cbTipoDoc.getSelectedIndex()==1){
         String admitidos="1234567890";
         admitidos();
         }*/

    }//GEN-LAST:event_tfNmrDocKeyTyped

    private void tfResidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResidActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfResidActionPerformed

    private void tfResidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfResidKeyTyped
        // TODO add your handling code here:
        String admitidos = "1234567890";
        if (!admitidos.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfResidKeyTyped

    private void tfQuarteiraoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuarteiraoKeyTyped
        // TODO add your handling code here:
        String admitidos = "1234567890";
        if (!admitidos.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfQuarteiraoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JComboBox cbProvinciaNasc;
    private javax.swing.JComboBox cbProvinciaResid;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JComboBox cbTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfApelido;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfDataNasc;
    private javax.swing.JTextField tfDistritoNasc;
    private javax.swing.JTextField tfNacionalidade;
    private javax.swing.JTextField tfNmrDoc;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfProf;
    private javax.swing.JTextField tfQuarteirao;
    private javax.swing.JTextField tfResid;
    private javax.swing.JTextField tfRua_av;
    // End of variables declaration//GEN-END:variables

//Classe q limita caracters nos campos
    class MeuDocument extends PlainDocument {

        int maximo;

        public MeuDocument(int max) {
            maximo = max;
        }

        public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
            if ((getLength() + str.length()) <= maximo) {
                super.insertString(offs, str, a);
            }
        }
    }

    @Override
    public void Desabilitar() {
        tfApelido.setEnabled(false);
        tfBairro.setEnabled(false);
        tfDataNasc.setEnabled(false);
        tfDistritoNasc.setEnabled(false);
        tfNacionalidade.setEnabled(false);
        tfNmrDoc.setEnabled(false);
        tfNome.setEnabled(false);
        tfQuarteirao.setEnabled(false);
        tfRua_av.setEnabled(false);
        tfResid.setEnabled(false);
        cbProvinciaNasc.setEnabled(false);
        cbProvinciaResid.setEnabled(false);
        cbSexo.setEnabled(false);
        cbTipoDoc.setEnabled(false);
        btn_atualizar.setEnabled(false);
        btn_cadastrar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        tfProf.setEnabled(false);
    }

    @Override
    public void Habilitar() {
        tfApelido.setEnabled(true);
        tfBairro.setEnabled(true);
        tfDataNasc.setEnabled(true);
        tfDistritoNasc.setEnabled(true);
        tfNacionalidade.setEnabled(true);
        tfNmrDoc.setEnabled(true);
        tfNome.setEnabled(true);
        tfQuarteirao.setEnabled(true);
        tfRua_av.setEnabled(true);
        tfProf.setEnabled(true);
        tfResid.setEnabled(true);
        cbProvinciaNasc.setEnabled(true);
        cbProvinciaResid.setEnabled(true);
        cbSexo.setEnabled(true);
        cbTipoDoc.setEnabled(true);
        btn_cadastrar.setEnabled(true);
        btn_cancelar.setEnabled(true);

    }

    @Override
    public void Limpar() {
        tfApelido.setText(null);
        tfBairro.setText(null);
        tfDataNasc.setText(null);
        tfDistritoNasc.setText(null);
        tfNacionalidade.setText(null);
        tfNmrDoc.setText(null);
        tfNome.setText(null);
        tfQuarteirao.setText(null);
        tfResid.setText(null);
        tfRua_av.setText(null);
        tfProf.setText(null);
        cbProvinciaNasc.setSelectedIndex(0);
        cbProvinciaResid.setSelectedIndex(0);
        cbSexo.setSelectedIndex(0);
        cbTipoDoc.setSelectedIndex(0);
    }

    public void novaPessoa() {

    }
}
